### PR TITLE
Rename package to avoid hackage conflicts

### PR DESCRIPTION
**Pull request by mjgpy3**
To avoid hackage conflicts with the fork we're forking from. :fork_and_knife:

### CODE REVIEW

**Comment by eborden** [comment]
Have we tried contacting hackage trustees to take ownership of the package instead of directly forking?

**Comment by eborden** [comment]
https://wiki.haskell.org/Taking_over_a_package

**Comment by eborden** [comment]
The maintainer section includes a frontrowed.com email and the github org is frontrowed, which is a strong argument for takeover. This is a Freckle package that we've lost control of with an employee departure.

**Review by eborden — CHANGES_REQUESTED** [review]
:point_up: requesting change of process

**Comment by mjgpy3** [comment]
@gregwebs, hi :wave: 

Do you have the ability to add [FreckleEngineering](https://hackage.haskell.org/user/FreckleEngineering) and me ([mjgpy3](https://hackage.haskell.org/user/mjgpy3)) to the maintainers list for this project?

**Comment by gregwebs** [comment]
@mjgpy3 you are added to the hackage maintainers. If your access is working, please remove me as a maintainer.

**Comment by mjgpy3** [comment]
@gregwebs done! Thank you.

**Pull request closed without merging**
